---
title: "FINAL FINAL FINAL"
output: html_notebook
---
```{r}
library("readxl")
event.df <- read_excel("EventsCalendar (1).xlsx")
```

```{r}
View(event.df)
```

```{r}
contains.free = function(str){
  return(length(grep("free", str, ignore.case = TRUE)))
}
tmp.df <- event.df[!is.na(event.df$Cost), ]
is.free <- lapply(tmp.df$Cost, contains.free)

expensive.events <- tmp.df[!is.na(tmp.df['Cost']) & is.free == 0,]

nrow(expensive.events)

```

```{r}
eed <- expensive.events[order(expensive.events$'Date From'), ]$`Date From`

time.between <- c()
for (i in 1:length(eed) - 1){
  time.between[i] <- difftime(eed[i+1], eed[i], units = c("days"))
}
tb.outliernt <- time.between[time.between < 100]

summary(time.between)
sd(time.between)
boxplot(time.between, horizontal = TRUE, xlab="Days Between Events", main="Paid Events")
```

```{r}
time.between <- c()
for (i in 1:length(event.df) - 1){
  time.between[i] <- difftime(eed[i+1], eed[i], units = c("days"))
}
tb.outliernt <- time.between[time.between < 100]

summary(time.between)
sd(time.between)
boxplot(time.between, horizontal = TRUE, xlab="Days Between Events", main="All Events")
```




















```{r}

event.dates <- event.df[order(event.df$`Date From`),]$`Date From`
length(event.dates)
daily.events <- numeric()
for (i in 2:length(event.dates)){
  if (event.dates[i] != event.dates[i-1]){
    daily.events <- c(daily.events, 1)
  }else{
    daily.events[length(daily.events)] = daily.events[length(daily.events)] + 1
  }
}
length(daily.events)


length(daily.events)

event.dates[1]
tail(event.dates)

difftime(event.dates[(length(event.dates))],event.dates[1],  units = c("days"))
1865 - 1322

for(i in 0:543){
  daily.events = c(daily.events, 0)
}



plot(table(daily.events), xlab="Number of Daily Events", ylab = "Frequency", main="All days")
```





```{r}
library('lubridate')
event.df$month <- month(event.df$`Date From`)

academic.year <- event.df[(event.df$month != 5 &
                          event.df$month != 6 &
                          event.df$month != 7 &
                          event.df$month != 8), ]
nrow(academic.year)

event.dates <- academic.year[order(academic.year$`Date From`),]$`Date From`
length(event.dates)
daily.events <- numeric()
for (i in 2:length(event.dates)){
  if (event.dates[i] != event.dates[i-1]){
    daily.events <- c(daily.events, 1)
  }else{
    daily.events[length(daily.events)] = daily.events[length(daily.events)] + 1
  }
}
length(daily.events)
head(academic.year$`Date From`)
#23 Days + 235 * 5
for(i in 0:(23 + 235*5 - length(daily.events))){
  daily.events = c(daily.events, 0)
}

plot(table(daily.events), xlab="Number of Daily Events", ylab = "Frequency", main="September-April")
```

```{r}
expensive.events$month <- month(expensive.events$`Date From`)
plot(table(expensive.events$month), main="Paid Events by Month", xlab="Month", ylab="Number of Events")
```

```{r}
date.df['freq'] + 1
```